### ISSUE TITLE
error authenticating the sender account

### ISSUE THREAD

**Issue by MatanTubul** [olucurious/PyFCM#123]
Hi,

for some reason i got the following traceback:
```
`Traceback (most recent call last):
  File "send_notification.py", line 23, in <module>
    result = push_service.notify_single_device(registration_id=registration_id, message_title=message_title, message_body=message_body)
  File "/usr/local/lib/python2.7/dist-packages/pyfcm/fcm.py", line 90, in notify_single_device
    return self.parse_responses()[-1:][0]
  File "/usr/local/lib/python2.7/dist-packages/pyfcm/baseapi.py", line 241, in parse_responses
    raise AuthenticationError("There was an error authenticating the sender account")
pyfcm.errors.AuthenticationError: There was an error authenticating the sender account
`
```
i took my api key directly from FireBase google console 

this is the Java code that i used in order to get the token.
```
`private static final String TAG = "MyFirebaseIIDService";

    @Override
    public void onTokenRefresh() {

        //Getting registration token
        String refreshedToken = FirebaseInstanceId.getInstance().getToken();

        //Displaying token on logcat
        Log.d(TAG, "Refreshed token: " + refreshedToken);

    }
`
```

**Comment by MatanTubul** [comment]
issue was resolved:

accedantely i took the "API_KEY" insetad "Server_Key"
