### ISSUE TITLE
unable to install using pip command in linux

### ISSUE THREAD

**Issue by hengnee** [olucurious/PyFCM#129]
I typed "pip install pyfcm" and "pip install git+https://github.com/olucurious/PyFCM.git" of which both did not work with errors:

Downloading/unpacking pyfcm
  Downloading pyfcm-1.2.9-py2-none-any.whl
Downloading/unpacking requests-toolbelt (from pyfcm)
  Downloading requests_toolbelt-0.7.1-py2.py3-none-any.whl (53kB): 53kB downloaded
Downloading/unpacking requests from https://pypi.python.org/packages/7e/ac/a80ed043485a3764053f59ca92f809cc8a18344692817152b0e8bd3ca891/requests-2.13.0-py2.py3-none-any.whl#md5=5e432dcf5bd1e3402ea1656700d99365 (from pyfcm)
  Downloading requests-2.13.0-py2.py3-none-any.whl (584kB): 584kB downloaded
Installing collected packages: pyfcm, requests-toolbelt, requests
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 295, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 672, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 902, in move_wheel_files
    pycompile=self.pycompile,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 214, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 204, in clobber
    os.makedirs(destdir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/pyfcm-1.2.9.dist-info'

Storing debug log for failure in /home/pi/.pip/pip.log

**Comment by olucurious** [comment]
Try "sudo pip install pyfcm" and "sudo pip install git+https://github.com/olucurious/PyFCM.git"

**Comment by hengnee** [comment]
@olucurious Thank you! It worked just fine now.

Did a _sudo pip search pyfcm_ to find out that I had the package successfully installed.
