### ISSUE TITLE
Can't import module

### ISSUE THREAD

**Issue by kryptonn** [olucurious/PyFCM#286]
When i just import module i get this error : 
Traceback (most recent call last):
  File "/var/www/myfolder/script.py", line 3, in <module>
    from pyfcm import FCMNotification
  File "/usr/local/lib/python2.7/dist-packages/pyfcm/__init__.py", line 14, in <module>
    from .fcm import FCMNotification
  File "/usr/local/lib/python2.7/dist-packages/pyfcm/fcm.py", line 564
    def async_notify_multiple_devices(self,params_list:list=[],timeout=5):
                                                      ^
SyntaxError: invalid syntax

Any idea on what's going on ?

i run it in a docker php:7.2-fpm image with python 2.7

**Comment by neeksor** [comment]
use a newer version of python.
