### ISSUE TITLE
How should we send multiple notifications with the updated API?

### ISSUE THREAD

**Issue by sgserg** [olucurious/PyFCM#338]
Attempting to use `async_notify_multiple_devices` yields
```
Traceback (most recent call last):
  File "src/coral/manager/push/android_push.py", line 63, in send
    result = self.push_service.async_notify_multiple_devices(params_list=plist)
  File "/usr/local/lib/python3.6/dist-packages/pyfcm/fcm.py", line 81, in async_notify_multiple_devices
    return self.send_async_request(payloads=payloads, timeout=timeout)
TypeError: send_async_request() got an unexpected keyword argument 'payloads'
```

**Comment by olucurious** [comment]
Please use v2.0.3

**Comment by sgserg** [comment]
Thanks for the quick response!
I've just updated the package with `pip install --upgrade pyfcm` and it ended up installing 2.0.0.

I'm on Python 3.6.9.
Could that be the reason?

**Comment by sgserg** [comment]
Tried pip-installing 2.0.3 from github, but it failed with google-auth being too old (2.22.0 being the  latest for Python  3.6 according to [this](https://pypi.org/project/google-auth/)).

Sending notification to a single device works fine, so there is no problem with auth in itself.

Is there a way we could make it work with older google-auth?

**Comment by olucurious** [comment]
Did you mean to say "make it work with newer google-auth?"

**Comment by sgserg** [comment]
No, unfortunately I’m stuck on an older version (at most 2.22.0), on which pyfcm 2.0.0 installed and seemingly works fine (except the multiple device issue).

**Comment by sgserg** [comment]
Changing  the requirement to 2.22.0 and installing `aiohttp` makes our tests pass on 2.0.3.

What might break due to this requirement change?

**Comment by olucurious** [comment]
Can you try the new version

**Comment by sgserg** [comment]
Could you please update setup.py too? (reference 2.22.0 instead of 2.29.0)

**Comment by sgserg** [comment]
Also, annotations import fails on 3.6.9:
```
  File "/usr/src/app/coral/PyFCM/pyfcm/__init__.py", line 14, in <module>
    from .fcm import FCMNotification
  File "/usr/src/app/coral/PyFCM/pyfcm/fcm.py", line 1, in <module>
    from .baseapi import BaseAPI
  File "/usr/src/app/coral/PyFCM/pyfcm/baseapi.py", line 1
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

**Comment by sgserg** [comment]
(also, **aiohttp** dependency still needs to be manually installed)

**Comment by sgserg** [comment]
one more thing: the following comma in **pyfcm/baseapi.py** seems to cause troubles for both iOS and Android:
```
 34         proxy_dict=None,
 35         env=None,
 36         json_encoder=None,
 37         adapter=None >>> , <<<<
 38     ):
```

**Comment by sathvik-grexit** [comment]
Can someone please help me with the structure of the payload that needs to be passed to `async_notify_multiple_devices()`
I have fcm_token, notification_title, notification_body, data_payload params that can be passed to the above function.

**Comment by sgserg** [comment]
@sathvik-grexit it's apparently the same as for a single `notify` you just make an array of those.

**Comment by sathvik-grexit** [comment]
https://github.com/olucurious/PyFCM/blob/master/pyfcm/fcm.py#L74

I think we will have to update here, instead of params_list, it should be params_map. The doc strings should be mentioned for the python dictionary.

**Comment by tronku** [comment]
@sgserg can you please add an example in readme or here?
older -
```
pushService.notify_multiple_devices(
        registration_ids=tokens,
        data_message=data
    )
```
what should be the new way?

**Comment by dr0g0** [comment]
> Attempting to use `async_notify_multiple_devices` yields
> 
> ```
> Traceback (most recent call last):
>    ...
>    ...
>   File "/usr/local/lib/python3.6/dist-packages/pyfcm/fcm.py", line 81, in async_notify_multiple_devices
>     return self.send_async_request(payloads=payloads, timeout=timeout)
> TypeError: send_async_request() got an unexpected keyword argument 'payloads'
> ```

fcm_tokens = []
notification_title = "Notification Title"
notification_body = "Notification Body"
data_payload = {}
params_list  =[{"fcm_token":fcm_token,"notification_title":notification_title,"notification_body":notification_body,"notification_image":'https://synak.pro/static/img/about-1.png',"data_payload":data_payload} for fcm_token in fcm_tokens]
result = push_service.async_notify_multiple_devices(
    params_list=params_list, timeout=5
)

**Comment by criptocoko** [comment]
"params_list =[{"fcm_token":fcm_token,"notification_title":notification_title,"notification_body":notification_body,"notification_image":'https://synak.pro/static/img/about-1.png',"data_payload":data_payload} for fcm_token in fcm_tokens]

result = push_service.async_notify_multiple_devices(params_list=params_list, timeout=5)" this doesn't make sense to me, why do we have to repeat the data for each key when its the same. 
Why not go back to send the list of registration_ids like we did in older versions?

**Comment by kebrick** [comment]
And does it make sense to repeat the parsing of params_list 
`payloads = [self.parse_payload(**params) for params in params_list]` 
first in async_notify_multiple_devices, and then in the called send_async_request method. It is clear that we can call send_async_request separately. But in the case of async_notify_multiple_devices, we increase the time and resource costs for execution with a large amount of data
