### ISSUE TITLE
exceptions must derive from BaseException

### ISSUE THREAD

**Issue by LawrenceK** [olucurious/PyFCM#344]
2024-06-24 22:59:52,074 [ERROR] deliveryagents.da_push_fcm: exceptions must derive from BaseException
Traceback (most recent call last):
...Snip
  File "/usr/local/lib/python3.9/site-packages/pyfcm/fcm.py", line 67, in notify
    return self.parse_response(response)
  File "/usr/local/lib/python3.9/site-packages/pyfcm/baseapi.py", line 195, in parse_response
    raise ("There was an error authenticating the sender account")
TypeError: exceptions must derive from BaseException

**Comment by LawrenceK** [comment]
Sorry already appears fixed
