### ISSUE TITLE
Current master fails on Python 2.7

### ISSUE THREAD

**Issue by Atheros1** [olucurious/PyFCM#50]
Here is the traceback. Deleting tornado.py fixes the problem.

Traceback (most recent call last):
  File "/home/vmint/virtualenvs/chatserver/tests/PyFCM/pushNotificationTests.py", line 1, in <module>
    from pyfcm import FCMNotification
  File "/home/vmint/virtualenvs/chatserver/tests/PyFCM/pyfcm/__init__.py", line 18, in <module>
    from .extensions.tornado import TornadoFCMNotification
  File "/home/vmint/virtualenvs/chatserver/tests/PyFCM/pyfcm/extensions/tornado.py", line 28
    return self.parse_response(response)
SyntaxError: 'return' with argument inside generator

**Comment by olucurious** [comment]
Fixed in https://github.com/olucurious/PyFCM/commit/5fbc3b2491d9782a618734c8aba3a981789ba711
